<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{ebf68f6f-cb24-4b94-876b-484c15003446}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[i := i + 1;

IpcDiagnostics();		// first way to implement the IPC diagnostics

IpcDiagnostics_2();		// second way to implement the IPC diagnostics
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="1" />
      <LineId Id="2" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="13" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>